### ISSUE TITLE
Improve source-documentation to be useful

### ISSUE THREAD

**Issue by MarieEckert** [FelixEcker/mawim#13]
Right now, the documentation within the source code (namely header files) is lackluster.
## TODO:
- [ ] Document all functions
- [ ] Document all types
- [ ] Document all macros
